services:
  magang-bn:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_API_URL=${PUBLIC_API_URL}
        - PUBLIC_PORTAL_URL=${PUBLIC_PORTAL_URL}
        - PUBLIC_COOKIE_DOMAIN=${DOMAIN_NAME}
    container_name: magang-bn-app
    restart: unless-stopped
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - PUBLIC_PORTAL_URL=${PUBLIC_PORTAL_URL}
      - PUBLIC_COOKIE_DOMAIN=${DOMAIN_NAME}
    networks:
      - proxy
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.magang-bn.rule=Host(`magang-bn.${DOMAIN_NAME}`)"
      - "traefik.http.routers.magang-bn.entrypoints=websecure"
      - "traefik.http.routers.magang-bn.tls.certresolver=myresolver"
      - "traefik.http.services.magang-bn.loadbalancer.server.port=3004"

networks:
  proxy:
    external: true
  backend:
    external: true
