services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_URL: ${DB_URL}
      CLIENT_URLS: ${CLIENT_URLS}
      API_KEY: ${API_KEY}
      SALT_ROUNDS: ${SALT_ROUNDS}
      ACCESS_TOKEN_EXPIRES: ${ACCESS_TOKEN_EXPIRES}
      REFRESH_TOKEN_EXPIRES: ${REFRESH_TOKEN_EXPIRES}
      REDIS_URL: ${REDIS_URL}
      COOKIE_DOMAIN: ${DOMAIN_NAME}
    volumes:
      - uploads:/app/public
    networks:
      - proxy
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-bn.rule=Host(`api-bn.${DOMAIN_NAME}`)"
      - "traefik.http.routers.api-bn.entrypoints=websecure"
      - "traefik.http.routers.api-bn.tls.certresolver=myresolver"
      - "traefik.http.services.api-bn.loadbalancer.server.port=${PORT}"

volumes:
  uploads:

networks:
  proxy:
    external: true
  backend:
    external: true


