services:
  apps-bn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apps-bn-app
    restart: unless-stopped
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - PUBLIC_PORTAL_URL=${PUBLIC_PORTAL_URL}
      - PUBLIC_COOKIE_DOMAIN=${DOMAIN_NAME}
    networks:
      - proxy
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apps-bn.rule=Host(`apps-bn.${DOMAIN_NAME}`)"
      - "traefik.http.routers.apps-bn.entrypoints=websecure"
      - "traefik.http.routers.apps-bn.tls.certresolver=myresolver"
      - "traefik.http.services.apps-bn.loadbalancer.server.port=${PORT:3001}"

networks:
  proxy:
    external: true
  backend:
    external: true
