ALTER TABLE "students" ADD COLUMN "picture_id" TEXT UNIQUE REFERENCES "attachments"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "teachers" ADD COLUMN "picture_id" TEXT UNIQUE REFERENCES "attachments"("id") ON DELETE SET NULL ON UPDATE CASCADE;
